---
extends: default

ignore: |
  cdk.out/

rules:
  line-length:
    max: 150
    level: warning
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
